/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class shandiankulishe_codes_base_ipc_nativeImpl_MemoryUtils */

#ifndef _Included_shandiankulishe_codes_base_ipc_nativeImpl_MemoryUtils
#define _Included_shandiankulishe_codes_base_ipc_nativeImpl_MemoryUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     shandiankulishe_codes_base_ipc_nativeImpl_MemoryUtils
 * Method:    Alloc
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_shandiankulishe_codes_base_ipc_nativeImpl_MemoryUtils_Alloc
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     shandiankulishe_codes_base_ipc_nativeImpl_MemoryUtils
 * Method:    Read
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_shandiankulishe_codes_base_ipc_nativeImpl_MemoryUtils_Read
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     shandiankulishe_codes_base_ipc_nativeImpl_MemoryUtils
 * Method:    Write
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_shandiankulishe_codes_base_ipc_nativeImpl_MemoryUtils_Write
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     shandiankulishe_codes_base_ipc_nativeImpl_MemoryUtils
 * Method:    Close
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_shandiankulishe_codes_base_ipc_nativeImpl_MemoryUtils_Close
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
